### ISSUE TITLE
Enhancement - change poll time

### ISSUE THREAD

**Issue by sfeakes** [999LV/NUT_UPS#4]
Looks like the poll time is hard coded to 5 minutes, is there any chance you can add a configuration option to change this?

**Comment by 999LV** [comment]
@sfeakes the NUT server is actually polled every 60 seconds. I chose that value as a trade off between reactivity and resources usage. The technical minimum poll interval is 10 seconds (heartbeat of python plugins). 
It is easy to change by editing the ‘self.pollinterval = 60’ line in the code

**Comment by sfeakes** [comment]
Thanks for the quick reply, that's really interesting.  The updates I see in Domoticz are every 5 minutes, I need to look into what's wrong on my setup.  Here is an example from the Voltage logs.

2018-04-05 09:35:00 | 120.1
2018-04-05 09:40:00 | 120.1
2018-04-05 09:45:00 | 120.1
2018-04-05 09:50:00 | 119
2018-04-05 09:55:00 | 119
2018-04-05 10:00:00 | 120.1
2018-04-05 10:05:00 | 120.1

**Comment by 999LV** [comment]
@sfeakes your NUT server (or equivalent) probably updates the data on 5 minutes intervals... the plugin only updates the domoticz devices if the data for a given device has changed (you may not see the change due to display rounding though)
That being said, the only thing that truly matters is the status data and I assume your NUT server does update that value immediately... that will be reported to the plugin within 60 seconds max.
